2211-Postman/grace-shopper

- client/features/home/Home.js
- server/db/index.js
- server/db/models/Order.js
- server/db/models/OrderDetails.js
- server/db/models/Product.js
- server/db/models/User.js
Created Order and OrderDetails models
edited Product and User models
created associations
tables created:
> 10 tier 1 models and associations

- client/features/auth/AuthForm.js
- client/features/auth/authSlice.js
- server/db/models/User.js
cannot login with blank email:
welcome msg after logging in shows correct email:
> fixed login issues & home welcome display

- server/api/index.js
- server/api/products.js
- server/api/users.js
http://localhost:8080/api/products/ (All Products)
http://localhost:8080/api/products/1 (Single Product)
I also tested PUT/POST/DELETE on POSTMAN
> Added all products and single product routes

- client/app/AppRoutes.js
- client/features/cart/Cart.js
- client/features/navbar/Navbar.js
added /cart route in `/client/app/AppRoutes.js` & added cart to navbar
not logged in:
logged in:
created dummy Cart component `/client/features/cart/Cart.js` so the app isn't broken when we visit /cart
> added route path to /cart

- server/api/products.js
- server/api/users.js
Instead of creating a new branch for users routes, I accidentally committed and pushed the user routes changes to this branch/ticket(originally only products routes). Therefore, I just merged the two into this ticket.
http://localhost:8080/api/products
http://localhost:8080/api/products/1
http://localhost:8080/api/users (Excluded password)
http://localhost:8080/api/users/3 (Excluded password)
Tested POST/PUT/DELETE for products/users
> added all products/users and single product/user routes

- script/seed.js
- server/api/index.js
- server/api/order.js
- server/api/users.js
- server/db/index.js
> added backend routes for orders

- client/features/auth/AuthForm.js
- client/features/auth/authSlice.js
- client/features/home/Home.js
- script/seed.js
- server/db/models/User.js
> Added firstName and lastName fields

- .npmrc
- client/app/store.js
- client/features/cart/cartSlice.js
- client/features/singleProduct/Info.js
connected cartSlice to SingleProduct component
cart state updating correctly with product after clicking purchase button in SingleProduct component
> 21 create slice for orders

- client/features/cart/cartSlice.js
- client/features/singleProduct/Info.js
added form validation to ensure qty does not exceed stock count 
(needed to add new methods to cart slice
> Added size and qty options on single product page

- client/app/AppRoutes.js
- client/features/cart/cartSlice.js
cart persists in localStorage:
> 53 tier 1 make cart persistent

- client/features/navbar/Navbar.js
> remove Users tab for non admin users

- client/features/singleProduct/ImageGrid.js
- client/features/singleProduct/Info.js
- client/features/singleProduct/SingleProduct.js
- script/seed.js
Added at least 3 diff angles for each product & also fixed spacing between the Single Product Page content and the nav bar
> added new images to DB

- client/features/cart/Cart.js
- client/features/cart/CartCard.js
- client/features/cart/CartSummary.js
- client/features/cart/EditCartItemForm.js
- client/features/cart/cartSlice.js
- client/features/products/ProductsCard.js
- client/features/products/productsSlice.js
- client/features/singleProduct/Info.js
- client/features/singleProduct/SingleProduct.js
- client/helpers.js
Specifically so  far implemented ability to change the qty
> Added ability to edit cart items from the cart page. 

- client/features/auth/AuthForm.js
- client/features/auth/muiAuthForm.js
> fixed auth forms. added mui styling

- client/app/AppRoutes.js
- client/features/products/CreateProduct.js
- client/features/products/Products.js
- client/features/products/ProductsCard.js
- client/features/products/productsSlice.js
- client/features/singleProduct/EditSingleProduct.js
- client/features/singleProduct/Info.js
- client/features/singleProduct/SingleProduct.js
- client/features/singleProduct/singleProductSlice.js
Finished admin user privileges (Create, Edit, Delete) with one minor bug
1. Not logged in and non-admin user view:
2. Admin only view:
> 43 tier 1 create admin componentpage

- client/app/AppRoutes.js
- client/features/auth/authSlice.js
- client/features/cart/cartSlice.js
- client/features/home/Home.js
- client/features/navbar/ResponsiveAppBar.js
- script/seed.js
- server/api/order.js
- server/api/users.js
- server/db/models/Order.js
able to get a user's unique cart from the database when logging in: 
logging out clears the cart:
logging to diff user gets their unique cart:
> 45 tier 1 passing cart to db

- client/features/products/CreateProduct.js
- client/features/products/Products.js
- client/features/singleProduct/EditSingleProduct.js
- client/features/singleProduct/Info.js
- client/features/singleProduct/SingleProduct.js
- client/features/users/UsersCard.js
- script/seed.js
1. Fix editForm bug (brand, size, and editbutton)
2. Style createProduct and editProduct forms
3. Format UserCard height
4. Comment out duplicates and add more data in seed.js
> 73 1 fix editform bug brand size and editbutton 2 style createproduct and editproduct forms 3 format usercard height

- client/features/auth/AuthForm.js
- client/features/auth/authSlice.js
- client/features/auth/muiAuthForm.js
- client/features/cart/Cart.js
- client/features/cart/CartSummary.js
- client/features/cart/cartSlice.js
- client/features/checkout/AddressForm.js
- client/features/checkout/Checkout.js
- client/features/checkout/CheckoutCard.js
- client/features/checkout/Review.js
- server/api/order.js
- ensure cart is emptied at checkout
- carried thru name and address to review page
> Made DB updates for checkout when user is logged in

- client/features/footer/Footer.js
> github link opens a new tab

- script/seed.js
> add two extra pair of shoes to db

- client/features/navbar/Navbar.js
- client/features/navbar/ResponsiveAppBar.js
> add cart badge
